/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface QuotaIntervalUsageResponse {
  accountId: string;
  coverageComplete: boolean;
  end: string | null;
  events: number | null;
  intervalId: string;
  models: QuotaIntervalUsageGroup[];
  observedAt: string;
  poolAttribution: boolean;
  projects: QuotaIntervalUsageGroup[];
  quotaView: QuotaHistoryView;
  scope: string;
  start: string | null;
  status: string;
  usage: TokenUsage | null;
}
export interface QuotaIntervalUsageGroup {
  events: number;
  id: string | null;
  label: string | null;
  usage: TokenUsage;
}
export interface TokenUsage {
  cacheWrite: number;
  cacheWriteCoverage: number;
  cacheWriteObservedInput: number;
  cached: number;
  input: number;
  output: number;
  reasoning: number;
  total: number;
  uncached: number;
}
export interface QuotaHistoryView {
  account: string;
  asOf: string;
  instance: string;
  revision: number;
}
