/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface QuotaHistoryResponse {
  indexReady: boolean;
  intervals: QuotaHistoryInterval[];
  next: QuotaHistoryCursor | null;
  scope: string;
  selections?: QuotaHistoryCursor[] | null;
  sourceHistoryComplete: boolean;
  view: QuotaHistoryView;
}
export interface QuotaHistoryInterval {
  accountId: string;
  boundaryAfter: string | null;
  boundaryKind: string;
  firstObservedAt: string;
  firstUsedPercent: number | null;
  id: string;
  key: QuotaHistoryKey;
  lastObservedAt: string;
  lastUsedPercent: number | null;
  limitId: string;
  limitName: string | null;
  nominalStart: string | null;
  poolKey: string;
  reportedReset: string | null;
  role: string;
  sampleCount: number;
  streamKey: string;
  tokenSampleEnd: string | null;
  tokenSampleStart: string | null;
  windowSeconds: string | null;
}
export interface QuotaHistoryKey {
  at: string;
  ordinal: number;
  snapshotId: string;
}
export interface QuotaHistoryCursor {
  before: QuotaHistoryKey;
  signature: string;
  view: QuotaHistoryView;
}
export interface QuotaHistoryView {
  account: string;
  asOf: string;
  instance: string;
  revision: number;
}
