/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AttributionConfidence = "verified" | "inferred" | "unknown";
export type DataQuality = "confirmed" | "quarantined" | "unknown";

export interface RequestEvidenceResponse {
  attribution: string;
  end: string;
  historyComplete: boolean;
  next: RequestEvidenceCursor | null;
  rows: RequestEvidenceRow[];
  scope: string;
  selectedAccount: string | null;
  selectedModel: string | null;
  selectionAttribution: string;
  start: string;
  threadId: string;
}
export interface RequestEvidenceCursor {
  afterId: string;
  afterTime: string;
}
export interface RequestEvidenceRow {
  accountConfidence: AttributionConfidence;
  at: string;
  id: string;
  model: string | null;
  observedAccount: string | null;
  observedProject: string | null;
  projectConfidence: AttributionConfidence;
  quality: DataQuality;
  turnId: string | null;
  usage: TokenUsage;
}
export interface TokenUsage {
  cacheWrite: number;
  cacheWriteCoverage: number;
  cacheWriteObservedInput: number;
  cached: number;
  input: number;
  output: number;
  reasoning: number;
  total: number;
  uncached: number;
}
