/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TurnEvidenceResponse {
  end: string;
  historyComplete: boolean;
  nextOffset: number | null;
  rows: TurnEvidenceRow[];
  scope: string;
  selectedAccount: string | null;
  selectedModel: string | null;
  start: string;
  threadId: string;
}
export interface TurnEvidenceRow {
  confirmedRequestCount: number;
  confirmedUsage: TokenUsage | null;
  firstAt: string;
  groupId: string;
  lastAt: string;
  requestCount: number;
  turnId: string | null;
}
export interface TokenUsage {
  cacheWrite: number;
  cacheWriteCoverage: number;
  cacheWriteObservedInput: number;
  cached: number;
  input: number;
  output: number;
  reasoning: number;
  total: number;
  uncached: number;
}
