/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TimeGrain = "hour" | "day" | "week" | "month";
export type PeriodKey = "today" | "week" | "rolling7" | "month" | "rolling30" | "weeks12" | "months12" | "lifetime";
export type PeriodWindowKind = "calendar" | "rolling" | "lifetime";
export type CollectionPhase = "idle" | "optimizing" | "compacting" | "backfill" | "syncing" | "live";
export type ExplorerProjectKind = "project" | "standalone_conversations" | "unmatched_records";
export type ExplorerSessionKind = "session" | "orphan_subagent";
export type QualitySeverity = "info" | "warning" | "critical";
export type DataQuality = "confirmed" | "quarantined" | "unknown";
export type SourceStatus = "fresh" | "delayed" | "offline";
export type MachineScope = "all_devices" | "this_machine";
export type MetricSource = "official" | "local" | "reconciled";
export type MetricStatus = "exact" | "lower_bound" | "local_sample" | "unknown";
export type MissingEstimateStatus = "conservative_floor" | "insufficient_coverage" | "not_applicable_to_single_account";
export type DataMode = "mock" | "http";
export type DisplayTotalKind =
  "official" | "official_plus_local_tail_lower_bound" | "local_lower_bound" | "not_applicable";
export type ReconciledAccountDayStatus = "exact_official" | "local_tail" | "local_only_account" | "unknown";
export type QuotaWindowKind = "weekly" | "short" | "custom" | "unknown";
export type QuotaPoolStatus = "healthy" | "warning" | "critical" | "unknown";
export type AttributionConfidence = "verified" | "inferred" | "unknown";
export type TimelineEventKind = "account_switch" | "quota_reset" | "quota_reset_scheduled";

export interface DashboardBundle {
  breakdowns: BreakdownsResponse;
  collection: CollectionStatus;
  explorer: ExplorerResponse;
  quality: QualityResponse;
  summary: SummaryResponse;
  timeseries: TimeseriesResponse;
}
export interface BreakdownsResponse {
  account: BreakdownRow[];
  generatedAt: string;
  model: BreakdownRow[];
  officialAccounts: OfficialAccountRow[];
  period: PeriodWindow;
  project: BreakdownRow[];
}
export interface BreakdownRow {
  confirmedEvents: number;
  description?: string | null;
  id: string;
  label: string;
  shareOfConfirmed: number;
  usage: QualityUsage;
}
export interface QualityUsage {
  confirmed: TokenUsage;
  quarantined: TokenUsage;
  unknown: TokenUsage;
}
export interface TokenUsage {
  cacheWrite: number;
  cacheWriteCoverage: number;
  cacheWriteObservedInput: number;
  cached: number;
  input: number;
  output: number;
  reasoning: number;
  total: number;
  uncached: number;
}
export interface OfficialAccountRow {
  active: boolean;
  authEpochCount: number;
  coverageStart: string | null;
  coverageThrough: string | null;
  firstSeenAt: string | null;
  id: string;
  label: string;
  lastSeenAt: string | null;
  lifetimeIsLowerBound: boolean;
  lifetimeTokens: number | null;
  monthIsLowerBound: boolean;
  monthTokens: number | null;
  observedAt: string | null;
  officialAvailable: boolean;
  planType: string | null;
  todayIsLowerBound: boolean;
  todayTokens: number | null;
  weekIsLowerBound: boolean;
  weekTokens: number | null;
}
export interface PeriodWindow {
  comparisonAvailable?: boolean | null;
  comparisonEnd?: string | null;
  comparisonStart?: string | null;
  coverageComplete?: boolean | null;
  coverageOffset?: number | null;
  coverageRatio?: number | null;
  coverageStart?: string | null;
  crossesMonth: boolean;
  crossesYear: boolean;
  defaultGrain?: TimeGrain | null;
  definition?: string | null;
  end: string;
  key: PeriodKey;
  label: string;
  partial?: boolean | null;
  start: string;
  timezone: string;
  windowKind: PeriodWindowKind;
}
export interface CollectionStatus {
  bytesRead: number;
  eventsInserted: number;
  itemsCompleted: number;
  itemsTotal: number;
  message?: string | null;
  mode: string;
  phase: CollectionPhase;
  rawRetentionDays: number;
  rollupComplete: boolean;
  rollupItemsCompleted: number;
  rollupItemsTotal: number;
  updatedAt: string;
}
export interface ExplorerResponse {
  generatedAt: string;
  period: PeriodKey;
  projects: ExplorerProject[];
  rankingWindows: ExplorerRankingWindows;
  selectedSession?: ExplorerSessionDetail | null;
  sessions: ExplorerSession[];
  stats: ExplorerStats;
}
export interface ExplorerProject {
  activeSessionCount: number;
  historicalSessionCount: number;
  historicalSubagentCount: number;
  id: string;
  kind: ExplorerProjectKind;
  label: string;
  lastActiveAt: string | null;
  lifetimeUsage: TokenUsage;
  monthPreviousUsage: TokenUsage;
  monthUsage: TokenUsage;
  orphanSubagentCount: number;
  periodEvents: number;
  periodUsage: TokenUsage;
  previousPeriodEvents: number;
  previousPeriodUsage: TokenUsage;
  recent15Events: number;
  recent15Usage: TokenUsage;
  sessionCount: number;
  sparkline: number[];
  subagentCount: number;
  todayUsage: TokenUsage;
  weekPreviousUsage: TokenUsage;
  weekUsage: TokenUsage;
}
export interface ExplorerRankingWindows {
  lifetime: PeriodWindow;
  month: PeriodWindow;
  week: PeriodWindow;
}
export interface ExplorerSessionDetail {
  createdAt: string;
  id: string;
  model: string | null;
  nodes: ExplorerSessionNode[];
  officialThreadUsage: OfficialThreadUsage | null;
  ownSamplingTimeline: SamplingTimelinePoint[];
  ownUsage: TokenUsage;
  presentInCodex: boolean;
  projectId: string | null;
  projectName: string | null;
  samplingGrain: TimeGrain;
  samplingTimeline: SamplingTimelinePoint[];
  subagentCount: number;
  title: string;
  treeUsage: TokenUsage;
  truncated: boolean;
  updatedAt: string;
}
export interface ExplorerSessionNode {
  agentNickname: string | null;
  agentPath: string | null;
  agentRole: string | null;
  archived: boolean;
  createdAt: string;
  depth: number;
  eventCount: number;
  id: string;
  model: string | null;
  ownUsage: TokenUsage;
  parentId: string | null;
  presentInCodex: boolean;
  projectId: string | null;
  projectName: string | null;
  relativeDepth: number;
  sourceKind: string;
  subtreeEventCount: number;
  subtreeUsage: TokenUsage;
  title: string;
  updatedAt: string;
}
export interface OfficialThreadUsage {
  estimatedUsageCreditsMicros: number;
  estimatedUsageUsdMicros: number | null;
  groups: OfficialThreadUsageGroup[];
  observedAt: string;
}
export interface OfficialThreadUsageGroup {
  cacheWriteInputTokens: number | null;
  cachedInputTokens: number | null;
  estimatedUsageCreditsMicros: number;
  inputTokens: number | null;
  model: string | null;
  netNewInputTokens: number | null;
  outputTokens: number | null;
  reasoningEffort: string | null;
  speed: string | null;
  totalTokens: number | null;
}
export interface SamplingTimelinePoint {
  bucket: string;
  events: number;
  usage: TokenUsage;
}
export interface ExplorerSession {
  active: boolean;
  archived: boolean;
  createdAt: string;
  eventCount: number;
  hasUserEvent: boolean;
  id: string;
  kind: ExplorerSessionKind;
  model: string | null;
  ownUsage: TokenUsage;
  presentInCodex: boolean;
  subagentCount: number;
  title: string;
  treeUsage: TokenUsage;
  updatedAt: string;
}
export interface ExplorerStats {
  activeSessions: number;
  historicalSessionCount: number;
  historicalSubagentCount: number;
  latestConfirmedAt?: string | null;
  lifetime: TokenUsage;
  localRecent15Events: number;
  localRecent15Minutes: TokenUsage;
  official: ExplorerOfficialStats;
  orphanSubagentCount: number;
  projectCount: number;
  selectedPeriod: TokenUsage;
  sessionCount: number;
  standaloneConversations: ExplorerStandaloneStats;
  subagentCount: number;
  today: TokenUsage;
  week: TokenUsage;
}
export interface ExplorerOfficialStats {
  accountCoverageComplete: boolean;
  backendIncludesToday: boolean;
  coverageThrough: string | null;
  knownAccountCount: number;
  lifetimeTokens: number | null;
  missingOfficialAccountCount: number;
  monthTokens: number | null;
  observedAt: string | null;
  peakDailyTokens: number | null;
  selectedPeriodTokens: number | null;
  todayTokens: number | null;
  totalIsLowerBound: boolean;
  verifiedAccountCount?: number | null;
  weekTokens: number | null;
}
export interface ExplorerStandaloneStats {
  current: number;
  historical: number;
  indexed: number;
  lifetimeUsage: TokenUsage;
  selectedPeriodUsage: TokenUsage;
  withLocalEvidence: number;
}
export interface QualityResponse {
  generatedAt: string;
  issues: QualityIssue[];
  reconstruction: ReconstructionSummary;
  sources: SourceHealth[];
  states: QualityStateSummary[];
  trustedPolicy: string;
}
export interface QualityIssue {
  detail: string;
  eventCount: number;
  firstSeen: string;
  id: string;
  lastSeen: string;
  severity: QualitySeverity;
  state: DataQuality;
  title: string;
  tokenCount: number | null;
}
export interface ReconstructionSummary {
  bytesProcessed: number;
  bytesTotal: number;
  pendingSources: number;
  reconstructedSources: number;
  reconstructingSources: number;
  selectedTokens: number;
  unrecoverableSources: number;
}
export interface SourceHealth {
  label: string;
  lagSeconds: number;
  lastObservedAt: string;
  machineLabel: string;
  sourceId: string;
  status: SourceStatus;
}
export interface QualityStateSummary {
  description: string;
  eventCount: number;
  state: DataQuality;
  tokenCount: number | null;
  usage: TokenUsage;
}
export interface SummaryResponse {
  attributionCoverage: AttributionCoverage;
  averagePerDay: number;
  cacheRate: number;
  comparison: SummaryComparison;
  confirmedEvents: number;
  filters: FilterCatalog;
  generatedAt: string;
  latestConfirmedAt: string | null;
  matchRate: number;
  metrics: SummaryMetrics;
  missingAccountEstimate: MissingAccountEstimate;
  mode: DataMode;
  official: OfficialUsageView;
  period: PeriodWindow;
  quotaCycles: QuotaCycle[];
  quotaPools: QuotaPool[];
  reconciliation: SummaryReconciliation;
  unmatchedEvents: number;
  usage: QualityUsage;
}
export interface AttributionCoverage {
  accountTotalTokens: number | null;
  canAllocateGapToProjects: boolean;
  coverageRatio: number | null;
  definitionId: string;
  gapBuckets: AttributionGapBucket[];
  localAttributedTokens: number;
  localComplementTokens: number;
  localEvidenceDayCount: number;
  localOnOfficialDays: number;
  localWindowStart: string | null;
  localWindowThrough: string | null;
  namedProjectTokens: number;
  officialBaseTokens: number;
  officialDayCount: number;
  officialWindowStart: string | null;
  officialWindowThrough: string | null;
  scope: string;
  selectedLocalTokens: number;
  standaloneConversationTokens: number;
  standaloneConversations: StandaloneConversationCoverage;
  unassignedTokens: number;
  unattributedTokens: number;
}
export interface AttributionGapBucket {
  detail: string;
  id: string;
  label: string;
  tokens: number;
}
export interface StandaloneConversationCoverage {
  current: number;
  historical: number;
  indexed: number;
  withLocalEvidence: number;
}
export interface SummaryComparison {
  available: boolean;
  deltaPercent: number | null;
  deltaTokens: number;
  previousEvents?: number | null;
  usage: TokenUsage;
}
export interface FilterCatalog {
  accounts: DimensionOption[];
  models: DimensionOption[];
  periods: PeriodOption[];
  projects: DimensionOption[];
}
export interface DimensionOption {
  description?: string | null;
  id: string;
  label: string;
}
export interface PeriodOption {
  description?: string | null;
  id: PeriodKey;
  label: string;
}
export interface SummaryMetrics {
  accountTotal: ResolvedMetric;
  localAttributedTotal: ResolvedMetric;
}
export interface ResolvedMetric {
  accountScope: string;
  coverage: MetricCoverage;
  definitionId: string;
  machineScope: MachineScope;
  source: MetricSource;
  status: MetricStatus;
  timezone: string;
  value: number | null;
  windowEnd: string | null;
  windowStart: string | null;
}
export interface MetricCoverage {
  complete: boolean;
  knownAccountCount: number;
  missingOfficialAccountCount: number;
  ratio: number;
}
export interface MissingAccountEstimate {
  alignedAccountDays: number;
  allocationRoundingDelta: number;
  applicable: boolean;
  byDay: MissingAccountEstimateDay[];
  byModel: MissingAccountEstimateBreakdown[];
  byProject: MissingAccountEstimateBreakdown[];
  canSplitByMissingAccount: boolean;
  capturedAccountCount: number;
  combinedUnobservedAccountCount: number;
  componentInvariantMismatchTokens: number;
  coverageStart: string | null;
  coverageThrough: string | null;
  definitionId: string;
  excessAccountDays: number;
  excludedAccountDays: number;
  isConservativeFloor: boolean;
  isEstimate: boolean;
  knownLocalCappedTokens: number;
  localAssignedOnAlignedDays: number;
  method: string;
  officialOnAlignedDays: number;
  rawResidualTokens: number;
  selectedUsage: TokenUsage;
  sourceAccountExcess: MissingSourceAccountExcess[];
  status: MissingEstimateStatus;
  totalUsage: TokenUsage;
}
export interface MissingAccountEstimateDay {
  date: string;
  sourceEvents: number;
  usage: TokenUsage;
}
export interface MissingAccountEstimateBreakdown {
  id: string;
  label: string;
  sourceEvents: number;
  usage: TokenUsage;
}
export interface MissingSourceAccountExcess {
  accountId: string;
  accountLabel: string;
  alignedDays: number;
  estimatedTokens: number;
  excessDays: number;
  localTokens: number;
  officialTokens: number;
}
export interface OfficialUsageView {
  accountCount: number;
  accountCoverage: OfficialAccountCoverage[];
  accountCoverageComplete: boolean;
  authoritativeForAccountTotal: boolean;
  backendIncludesToday: boolean;
  bucketTotalTokens: number;
  commonCoverageStart: string | null;
  commonCoverageThrough: string | null;
  comparisonPoints: OfficialUsagePoint[];
  coverageComplete: boolean;
  coverageRatio: number;
  coverageStart: string | null;
  coverageThrough: string | null;
  deltaPercent: number | null;
  deltaTokens: number | null;
  displayDeltaPercent: number | null;
  displayDeltaTokens: number | null;
  displayIsLowerBound: boolean;
  displayPreviousTotalTokens: number | null;
  displayTotalKind: DisplayTotalKind;
  displayTotalTokens: number | null;
  granularity: TimeGrain;
  identityScopeComplete: boolean;
  knownAccountCount: number;
  lastError: string | null;
  latestCoverageThrough: string | null;
  lifetimeTokens: number | null;
  localComplementTokens: number;
  localTailStart: string | null;
  localTailTokens: number;
  missingAccountLocalTokens: number;
  missingOfficialAccountCount: number;
  observedAccountCount: number;
  observedAt: string | null;
  peakDailyTokens: number | null;
  periodExact: boolean;
  points: OfficialUsagePoint[];
  previousDisplayIsLowerBound: boolean;
  previousTotalTokens: number | null;
  primaryScope: boolean;
  provisionalIdentityCount: number;
  provisionalLocalTokens: number;
  reconciledComparisonPoints: ReconciledAccountDay[];
  reconciledPoints: ReconciledAccountDay[];
  source: string;
  totalIsLowerBound: boolean;
  totalTokens: number | null;
  unobservedAccountCount: number;
  userConfirmedAccountCount: number | null;
  verifiedAccountCount: number;
}
export interface OfficialAccountCoverage {
  accountId: string;
  coverageStart: string | null;
  coverageThrough: string | null;
  officialAvailable: boolean;
}
export interface OfficialUsagePoint {
  date: string;
  tokens: number;
}
export interface ReconciledAccountDay {
  coveredAccounts: number;
  date: string;
  knownAccounts: number;
  localOnlyTokens: number;
  localTailTokens: number;
  officialTokens: number;
  status: ReconciledAccountDayStatus;
  value: number;
}
export interface QuotaCycle {
  accountId: string;
  accountLabel: string;
  cycleEnd: string | null;
  cycleStart: string | null;
  empiricalRatioIsConversion: boolean;
  empiricalTokensPerUsedPercent: number | null;
  firstObservedAt: string;
  firstUsedPercent: number | null;
  id: string;
  label: string;
  lastObservedAt: string;
  limitId: string;
  localCoverageRatio: number | null;
  localEvents: number;
  localObservationStart: string;
  localUsage: TokenUsage;
  role: string;
  sampleCount: number;
  usedDeltaPercent: number | null;
  usedPercent: number | null;
  windowKind: QuotaWindowKind;
  windowMinutes: number | null;
}
export interface QuotaPool {
  accountId: string;
  accountLabel: string;
  detail?: string | null;
  id: string;
  label: string;
  limitId: string;
  observedAt: string;
  resetsAt: string | null;
  stale: boolean;
  status: QuotaPoolStatus;
  usedPercent: number | null;
  windowMinutes: number | null;
}
export interface SummaryReconciliation {
  attributionGapTokens: number | null;
  comparable: boolean;
  localAttributedTokens: number;
  localCoverageComplete: boolean;
  officialTotalTokens: number | null;
  reason: string;
}
export interface TimeseriesResponse {
  comparisonPoints: TimeseriesComparisonPoint[];
  generatedAt: string;
  grain: TimeGrain;
  official: OfficialUsageView;
  period: PeriodWindow;
  points: TimeseriesPoint[];
  projectSeries: ProjectSeries[];
  timeline: TimelineEvent[];
}
export interface TimeseriesComparisonPoint {
  confirmed: TokenUsage;
  confirmedEvents: number;
  date: string;
}
export interface TimeseriesPoint {
  confirmed: TokenUsage;
  confirmedEvents: number;
  date: string;
  quarantined: TokenUsage;
  quarantinedEvents: number;
  unknown: TokenUsage;
  unknownEvents: number;
}
export interface ProjectSeries {
  id: string;
  label: string;
  points: TimeseriesComparisonPoint[];
  totalTokens: number;
}
export interface TimelineEvent {
  accountId: string | null;
  at: string;
  confidence: AttributionConfidence;
  detail: string;
  id: string;
  kind: TimelineEventKind;
  title: string;
}
